name: Django CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
            POSTGRES_DB: test_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        flake8 . count --exit-zero --max-complexity 10 --max-line-length 120 --statistics
    - name: Run tests
      env:
        SECRET_KEY: 'test_key'
        DEBUG: 'True'
        ALLOWED_HOSTS: '127.0.0.1,localhost'
        DB_NAME: 'test_db'
        DB_USER: 'postgres'
        DB_PASSWORD: 'password'
        DB_HOST: 'localhost'
        DB_PORT: '5432'
      run: |
        unittest